AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for a Node.js Lambda function with a layer.

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - x86_64

Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyCustomLayer
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs18.x
      CompatibleArchitectures:
        - x86_64
      Description: Custom layer with utility functions.

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: dist/app.handler
      Layers:
        - !Ref MyLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"